#:schema node_modules/wrangler/config-schema.json
name = "singsub-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SINGSUB_KV", id = "" }
]
